steps:

- name: 'gcr.io/cloud-builders/docker'
  id: build
  args: [
    'build',
    '-t', '${_BASE_IMAGE_NAME}:latest',
    '-t', '${_BASE_IMAGE_NAME}:${TAG_NAME}',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: test
  args: [
    'run',
    '--rm',
    '--entrypoint', 'py.test',
    '${_BASE_IMAGE_NAME}:latest'
  ]
  waitFor: [ 'build' ]

images:
 - '${_BASE_IMAGE_NAME}:latest'
 - '${_BASE_IMAGE_NAME}:${TAG_NAME}'
timeout: 600s
substitutions:
  _BASE_IMAGE_NAME: 'gcr.io/${PROJECT_ID}/github-globalfishingwatch-pipe-vms-research'
options:
  dynamic_substitutions: true
